const default_list = [
    {
      "id": "uuid_generate_v4()",
      "name": "Gangsta 7\" Vinyl",
      "artist": "Free Nationals",
      "image": "/free_1.png",
      "price": 22.99,
      "state": true,
      "description": "A 7-inch vinyl by Free Nationals.",
      "genre": "uuid_generate_v4()",
      "format": "Single",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "FAMILY LP",
      "artist": "DJ Scheme",
      "image": "/Scheme_1.png",
      "price": 20.99,
      "state": true,
      "description": "An LP by DJ Scheme.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "Wont He Do It Vinyl (Bone)",
      "artist": "Conway the Machine",
      "image": "/ConwaytheMachine_1.png",
      "price": 24.99,
      "state": true,
      "description": "A bone vinyl by Conway the Machine.",
      "genre": "uuid_generate_v4()",
      "format": "Single",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "Glockoma 2 Vinyl (Deluxe)",
      "artist": "Key Glock",
      "image": "/Key_1.png",
      "price": 23.99,
      "state": true,
      "description": "Deluxe vinyl by Key Glock.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "You Only Live 2wice Vinyl",
      "artist": "Freddie Gibbs",
      "image": "/FreddieGibbs_1.png",
      "price": 23.99,
      "state": true,
      "description": "A vinyl by Freddie Gibbs.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "U Wasnt There",
      "artist": "Camron & A-Trak",
      "image": "/Camron_1.png",
      "price": 23.99,
      "state": true,
      "description": "A vinyl by Camron & A-Trak.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "Gangsta 7\" Vinyl",
      "artist": "Free Nationals",
      "image": "/free_1.png",
      "price": 22.99,
      "state": true,
      "description": "A 7-inch vinyl by Free Nationals.",
      "genre": "uuid_generate_v4()",
      "format": "Single",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "FAMILY LP",
      "artist": "DJ Scheme",
      "image": "/Scheme_1.png",
      "price": 20.99,
      "state": true,
      "description": "An LP by DJ Scheme.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "Wont He Do It Vinyl (Bone)",
      "artist": "Conway the Machine",
      "image": "/ConwaytheMachine_1.png",
      "price": 24.99,
      "state": true,
      "description": "A bone vinyl by Conway the Machine.",
      "genre": "uuid_generate_v4()",
      "format": "Single",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "Glockoma 2 Vinyl (Deluxe)",
      "artist": "Key Glock",
      "image": "/Key_1.png",
      "price": 23.99,
      "state": true,
      "description": "Deluxe vinyl by Key Glock.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "You Only Live 2wice Vinyl",
      "artist": "Freddie Gibbs",
      "image": "/FreddieGibbs_1.png",
      "price": 23.99,
      "state": true,
      "description": "A vinyl by Freddie Gibbs.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    },
    {
      "id": "uuid_generate_v4()",
      "name": "U Wasnt There",
      "artist": "Camron & A-Trak",
      "image": "/Camron_1.png",
      "price": 23.99,
      "state": true,
      "description": "A vinyl by Camron & A-Trak.",
      "genre": "uuid_generate_v4()",
      "format": "LP",
      "release_date": "2023-01-01",
      "sold": 0
    }
  ]
  
  module.exports = default_list;